1. Create a 1D NumPy Array

In [12]:
import numpy as np
temperature_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperature_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


2. Inspection and Properties

In [14]:
temperature_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Shape:",temperature_w1.shape)
print("Data Type:",temperature_w1.dtype)
print("Number of Element:",temperature_w1.size)

Shape: (7,)
Data Type: float64
Number of Element: 7


3. Array Operations
(Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32)

In [17]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

fahrenheit = (temperatures_w1 * 9/5) + 32
print(fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


Find the maximum, minimum, and mean temperatures for the week.

In [19]:
print("Maximum:", temperatures_w1.max())
print("Minimum:", temperatures_w1.min())
print("Mean:", temperatures_w1.mean())

Maximum: 26.1
Minimum: 20.8
Mean: 23.542857142857144


4. Array Slicing and Indexing

Extract the temperatures for the first three days of the week.

In [20]:
print("First three days:", temperatures_w1[:3])

First three days: [22.5 25.3 20.8]


Extract the temperatures for the weekend (last two days).


In [21]:
print("Last two days:",temperature[-2:])

Last two days: [24.8 21.9]


Extract the temperatures for the middle three days of the week.

In [22]:
print("Middle three days:",temperature[2:5])

Middle three days: [20.8 23.4 26.1]


5. Create a 2D Array

In [25]:
import numpy as np
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


6. Inspect and Slice the 2D Array
Inspect and print the shape, data type, and total number of elements in the
temperatures array.

In [27]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Total elements: 14


Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [28]:
import numpy as np

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])

print("Weekends:", temperatures[:, -2:])

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekends: [[24.8 21.9]
 [22.8 20.1]]


Pandas Series:
1. Creating Pandas Series:
 Create a Pandas Series named marks with the following data

In [29]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


2. Indexing and Slicing:
Use the integer index position to access the mark of the 1st rank student.

In [44]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("1st rank:", marks[0])


1st rank: 95


/tmp/ipykernel_6294/731196942.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("1st rank:", marks[0])


Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels.

In [45]:
print("Top 3 ranks:")
print(marks.loc['Rank1':'Rank3'])


Top 3 ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64


Use the iloc accessor to retrieve the mark of the 3rd rank student.

In [46]:
print("3rd rank mark:", marks.iloc[2])

3rd rank mark: 89


Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.

In [47]:
print("Marks greater than 90:")
print(marks[marks > 90])

Marks greater than 90:
Rank1    95
Rank2    92
dtype: int64


3. Manipulating Series:

In [48]:
marks.loc['Rank1'] = 100
print("After updating Rank1:")
print(marks)

After updating Rank1:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


Remove the entry corresponding to the last rank from the Series.


In [49]:
marks = marks.drop('Rank5')
print("After removing last rank:")
print(marks)

After removing last rank:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


Compute the CGPA by dividing each mark in the Series by 10.

In [50]:
cgpa = marks / 10
print("CGPA:")
print(cgpa)

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


Pandas DataFrame:
1. Creating Pandas DataFrame:
Create a Pandas DataFrame named transactions with the following data:

In [51]:
import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
})

print(transactions)

   TransactionID
0            101
1            102
2            103
3            104
4            105
5            106
6            107
7            108
8            109
9            110


ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'

In [52]:
transactions['ProductCategory'] = [
    'Electronics', 'Clothing', 'Electronics', 'Furniture',
    'Clothing', 'Electronics', 'Furniture', 'Clothing',
    'Furniture', 'Electronics'
]

print(transactions)

   TransactionID ProductCategory
0            101     Electronics
1            102        Clothing
2            103     Electronics
3            104       Furniture
4            105        Clothing
5            106     Electronics
6            107       Furniture
7            108        Clothing
8            109       Furniture
9            110     Electronics


Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'

In [54]:
region = [
    'North', 'South', 'North', 'East', 'West',
    'North', 'East', 'West', 'South', 'North'
]

transactions['Region'] = region
print(transactions)

   TransactionID ProductCategory Region
0            101     Electronics  North
1            102        Clothing  South
2            103     Electronics  North
3            104       Furniture   East
4            105        Clothing   West
5            106     Electronics  North
6            107       Furniture   East
7            108        Clothing   West
8            109       Furniture  South
9            110     Electronics  North


Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [55]:
transactions['Amount'] = [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


2. Data Exploration:
Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types.

In [56]:
print("Complete DataFrame:")
print(transactions)

print("\nHead:",transactions.head())

print("\nTail:",transactions.tail())

print("\nShape:",transactions.shape)

print("\nColumn Names:",transactions.columns)

print("\nData Types:",transactions.dtypes)


Complete DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head:    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail:    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7     

Display only the 'ProductCategory' and 'Amount' columns.


In [57]:
print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


Retrieve the last 3 columns of the DataFrame using iloc or loc.


In [58]:
print(transactions.iloc[:, 1:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.


In [59]:
filtered_rows = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(filtered_rows)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


Find the value counts for the 'ProductCategory' column.


In [60]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


Find the unique values in the 'Region' column.


In [61]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


Group by 'Region' and find the mean amount for each region.


In [62]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


3. Manipulating the DataFrame:
Modify the 'Amount' for the transaction with TransactionID 102 to 165.

In [63]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


Add a new column 'Discount' by calculating 10% of the 'Amount'


In [65]:
transactions['Discount'] = transactions['Amount'] / 10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


Remove the row with TransactionID 109.

In [67]:
transactions = transactions.drop(
    transactions[transactions['TransactionID'] == 109].index
)
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


Delete the 'Discount' column from the DataFrame.

In [68]:
del transactions['Discount']

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
